---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: wego-github-podinfo
  namespace: wego-system
spec:
  interval: 30s
  ref:
    branch: master
  secretRef:
    name: wego-github-podinfo
  url: ssh://git@github.com/Wopf/podinfo.git

