---
apiVersion: wego.weave.works/v1alpha1
kind: Application
metadata:
  labels:
    wego.weave.works/app-identifier: wego-a6e42ff9a620d9cfc4b87ce1666cbd7e
  name: podinfo
  namespace: wego-system
spec:
  branch: main
  config_url: ssh://git@github.com/Wopf/podinfo.git
  deployment_type: kustomize
  path: ./
  source_type: git
  url: ssh://git@github.com/Wopf/podinfo.git
