---
apiVersion: wego.weave.works/v1alpha1
kind: Application
metadata:
  labels:
    wego.weave.works/app-identifier: wego-483b2b589afc9172e0f1d40d7a4cac78
  name: podinfo
  namespace: wego-system
spec:
  branch: master
  deployment_type: kustomize
  path: ./
  source_type: git
  url: ssh://git@github.com/Wopf/podinfo.git
